# -*- coding: utf-8 -*-
"""Caso Práctico.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1U3fzLQqqtQ_UFY_daQzkTSn3Ii4pDSB9
"""

# gráfico ejercicio 1.1.
import matplotlib.pyplot as plt

datos = [18, 22, 25, 27, 29, 30, 31, 33, 35, 36, 38, 40, 42, 45, 98]

fig, ax = plt.subplots(figsize=(10, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

bp = ax.boxplot(
    datos,
    vert=False,
    patch_artist=True,
    boxprops=dict(facecolor='#8AA4C4', color='#2C3E50', linewidth=1.5),
    whiskerprops=dict(color='#2C3E50', linewidth=1.5),
    capprops=dict(color='#2C3E50', linewidth=1.5),
    medianprops=dict(color='#FFFFFF', linewidth=2.5),
    flierprops=dict(
        marker='o',
        markerfacecolor='#5C7AEA',
        markeredgecolor='#2C3E50',
        markersize=8,
    ),
)

ax.axvline(27, color='#2C3E50', linestyle='--', linewidth=1.2, label='Q1 = 27')
ax.axvline(40, color='#2C3E50', linestyle='--', linewidth=1.2, label='Q3 = 40')
ax.axvline(
    7.5,
    color='#64748B',
    linestyle=':',
    linewidth=1.2,
    label='Límite Inf. = 7.5',
)
ax.axvline(
    59.5,
    color='#64748B',
    linestyle=':',
    linewidth=1.2,
    label='Límite Sup. = 59.5',
)

# RIC
ax.plot([], [], ' ', label='RIC = 13')


ax.annotate(
    'LI: 7.5',
    (7.5, 0.72),
    ha='center',
    va='top',
    fontsize=8.5,
    fontweight='bold',
    color='#2C3E50',
)
ax.annotate(
    'LS: 59.5',
    (59.5, 0.72),
    ha='center',
    va='top',
    fontsize=8.5,
    fontweight='bold',
    color='#2C3E50',
)
ax.annotate(
    '98 (Atípico)',
    (98, 1.08),
    ha='center',
    va='bottom',
    fontsize=9,
    fontweight='bold',
    color='#2C3E50',
)

ax.set_title(
    'Distribución de Montos por Pedido (en miles de ₡)',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_xlabel(
    'Monto (miles de ₡)', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_yticks([])

ax.grid(True, linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9)


ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9,
)

for spine in ax.spines.values():
    spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)

plt.tight_layout()
plt.show()

# gráfico ejercicio 1.2.
import matplotlib.pyplot as plt

fig, ax = plt.subplots(figsize=(10, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

box_stats = [{
    'label': 'Tiempo de entrega',
    'whislo': 1,
    'q1': 2,
    'med': 3,
    'q3': 4,
    'whishi': 6,
    'fliers': [14],
}]

bp = ax.bxp(
    box_stats,
    vert=False,
    patch_artist=True,
    boxprops=dict(facecolor='#8AA4C4', color='#2C3E50', linewidth=1.5),
    whiskerprops=dict(color='#2C3E50', linewidth=1.5),
    capprops=dict(color='#2C3E50', linewidth=1.5),
    medianprops=dict(color='#FFFFFF', linewidth=2.5),
    flierprops=dict(
        marker='o',
        markerfacecolor='#5C7AEA',
        markeredgecolor='#2C3E50',
        markersize=8,
    ),
)


ax.axvline(
    2, color='#2C3E50', linestyle='--', linewidth=1.2, label='Q1 = 2 días'
)
ax.axvline(
    4, color='#2C3E50', linestyle='--', linewidth=1.2, label='Q3 = 4 días'
)
ax.axvline(
    7,
    color='#64748B',
    linestyle=':',
    linewidth=1.2,
    label='Límite Sup. = 7 días',
)


ax.plot([], [], ' ', label='RIC = 2 días')
ax.plot([], [], ' ', label='Límite Inf. = -1 día')


ax.annotate(
    'LS: 7d',
    (7, 0.72),
    ha='center',
    va='top',
    fontsize=8.5,
    fontweight='bold',
    color='#2C3E50',
)
ax.annotate(
    '14d (Atípico)',
    (14, 1.08),
    ha='center',
    va='bottom',
    fontsize=9,
    fontweight='bold',
    color='#2C3E50',
)

ax.set_title(
    'Resumen de Tiempos de Entrega de Pedidos',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_xlabel(
    'Tiempo de entrega (días)', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_yticks([])

ax.grid(True, linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9)


ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9,
)

for spine in ax.spines.values():
    spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)

plt.tight_layout()
plt.show()

# gráfico ejercicio 1.3.
import matplotlib.pyplot as plt

productos = ['Producto A', 'Producto B']
media = [45000, 18000]
cv = [15, 30]

fig, ax1 = plt.subplots(figsize=(9, 4.5), facecolor='white')
ax1.set_facecolor('#D0DCEB')

bars = ax1.bar(productos, media, color='#8AA4C4', width=0.4, edgecolor='#2C3E50', label='Venta Media (₡)')
ax1.set_ylabel('Venta Media (₡)', fontsize=10, fontstyle='italic', color='#1A2530')

ax2 = ax1.twinx()
line = ax2.plot(productos, cv, color='#5C7AEA', marker='o', linewidth=2.5, markersize=8, label='CV (%)')
ax2.set_ylabel('Coeficiente de Variación (%)', fontsize=10, fontstyle='italic', color='#1A2530')

for bar in bars:
    yval = bar.get_height()
    ax1.annotate(f'₡{yval:,.0f}', (bar.get_x() + bar.get_width()/2, yval/2),
                 ha='center', va='center', color='#FFFFFF', fontweight='bold', fontsize=9.5)

for i, txt in enumerate(cv):
    ax2.annotate(f'{txt}%', (productos[i], cv[i] + 1), ha='center', va='bottom',
                 color='#2C3E50', fontweight='bold', fontsize=9.5)

plt.title('Comparación de Media y Variabilidad Relativa (CV)', fontsize=13, fontweight='bold', pad=15, color='#1A2530')

ax1.grid(True, linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9)

lines1, labels1 = ax1.get_legend_handles_labels()
lines2, labels2 = ax2.get_legend_handles_labels()
ax1.legend(lines1 + lines2, labels1 + labels2, loc='center left', bbox_to_anchor=(1.12, 0.5), frameon=True, facecolor='#F0F4F8', edgecolor='#CBD5E1', fontsize=9.5)

for spine in ax1.spines.values():
    spine.set_visible(False)
for spine in ax2.spines.values():
    spine.set_visible(False)

fig.text(0.42, -0.03, 'Estudiante: Katherine Susana Rojas Saborío', ha='center', fontsize=9, fontstyle='italic', color='#4A5568')
plt.tight_layout()
plt.show()

# gráfico ejercicio 1.3 (asimetría)
import matplotlib.pyplot as plt
import numpy as np

np.random.seed(42)
datos_ventas = np.random.gamma(shape=3, scale=12000, size=1000) + 9000

media = np.mean(datos_ventas)
mediana = np.median(datos_ventas)

fig, ax = plt.subplots(figsize=(9, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

counts, bins, patches = ax.hist(
    datos_ventas,
    bins=25,
    color='#8AA4C4',
    edgecolor='#2C3E50',
    alpha=0.85,
)

ax.axvline(
    mediana,
    color='#2C3E50',
    linestyle='--',
    linewidth=1.8,
    label=f'Mediana = ₡{mediana:,.0f}',
)
ax.axvline(
    media,
    color='#5C7AEA',
    linestyle='-',
    linewidth=1.8,
    label=f'Media = ₡{media:,.0f}',
)

ax.annotate(
    'Cola a la derecha\n(Asimetría Positiva)',
    xy=(media + 15000, max(counts) * 0.4),
    xytext=(media + 25000, max(counts) * 0.6),
    arrowprops=dict(
        arrowstyle='->', color='#2C3E50', lw=1.2, connectionstyle='arc3,rad=-0.2'
    ),
    fontsize=9,
    fontweight='bold',
    color='#2C3E50',
)

ax.set_title(
    'Distribución de Ventas Diarias - Producto A',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_xlabel(
    'Monto de Venta (₡)', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_ylabel(
    'Frecuencia (Días)', fontsize=10, fontstyle='italic', color='#1A2530'
)

ax.set_axisbelow(True)
ax.grid(
    True, axis='y', linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9
)

ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9.5,
)

for spine in ax.spines.values():
  spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)

plt.tight_layout()
plt.show()

# gráfico ejercicio 2.2.
import matplotlib.pyplot as plt
import numpy as np

casos = ['Caso A', 'Caso B', 'Caso C']
p_valores = [0.032, 0.184, 0.049]
alphas = [0.05, 0.05, 0.01]
decisiones = ['Se rechaza H₀', 'No se rechaza H₀', 'No se rechaza H₀']

x = np.arange(len(casos))
width = 0.35

fig, ax = plt.subplots(figsize=(8.5, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

rects1 = ax.bar(
    x - width / 2,
    p_valores,
    width,
    label='Valor p',
    color='#5C7AEA',
    edgecolor='#2C3E50',
)
rects2 = ax.bar(
    x + width / 2,
    alphas,
    width,
    label='Nivel α',
    color='#8AA4C4',
    edgecolor='#2C3E50',
)

for i in range(len(casos)):
  ax.annotate(
      f'{p_valores[i]}',
      (x[i] - width / 2, p_valores[i] + 0.003),
      ha='center',
      va='bottom',
      fontsize=8.5,
      fontweight='bold',
      color='#1A2530',
  )
  ax.annotate(
      f'{alphas[i]}',
      (x[i] + width / 2, alphas[i] + 0.003),
      ha='center',
      va='bottom',
      fontsize=8.5,
      fontweight='bold',
      color='#1A2530',
  )

  max_h = max(p_valores[i], alphas[i])
  ax.annotate(
      decisiones[i],
      (x[i], max_h + 0.02),
      ha='center',
      va='bottom',
      fontsize=8.5,
      fontweight='bold',
      color='#2C3E50',
      bbox=dict(
          boxstyle='round,pad=0.3',
          facecolor='#F0F4F8',
          edgecolor='#CBD5E1',
          lw=0.8,
      ),
  )

ax.set_title(
    'Comparación de Valor p vs. Nivel de Significancia (α)',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_ylabel(
    'Probabilidad', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_xticks(x)
ax.set_xticklabels(casos, fontweight='bold', color='#1A2530')
ax.set_ylim(0, 0.25)

ax.set_axisbelow(True)
ax.grid(
    True, axis='y', linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9
)

ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9.5,
)

for spine in ax.spines.values():
  spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)

plt.tight_layout()
plt.show()

# gráfico ejercicio 3.2.
import matplotlib.pyplot as plt

canales = ['Tienda Física', 'Tienda en Línea']
medias = [32500, 38900]

fig, ax = plt.subplots(figsize=(8, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')


bars = ax.bar(
    canales,
    medias,
    color=['#8AA4C4', '#5C7AEA'],
    edgecolor='#2C3E50',
    width=0.45,
)

for bar in bars:
  yval = bar.get_height()
  ax.annotate(
      f'₡{yval:,.0f}',
      (bar.get_x() + bar.get_width() / 2, yval / 2),
      ha='center',
      va='center',
      color='#FFFFFF',
      fontweight='bold',
      fontsize=10.5,
  )

ax.set_title(
    'Monto Promedio de Compra por Canal de Venta',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_ylabel(
    'Monto Promedio (₡)', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_xlabel(
    'Canal de venta', fontsize=10, fontstyle='italic', color='#1A2530'
)

ax.set_axisbelow(True)
ax.grid(
    True, axis='y', linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9
)

ax.plot([], [], ' ', label='p-valor = 0.021\n(Diferencia Significativa)')
ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9.5,
)

for spine in ax.spines.values():
  spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)
plt.tight_layout()
plt.show()

# gráfico ejercicio 4.1.
import matplotlib.pyplot as plt

plataformas = ['Anterior', 'Nueva']
tiempos = [10.0, 9.6]  #Son para visualizar, no son reales

fig, ax = plt.subplots(figsize=(7, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

bars = ax.bar(
    plataformas,
    tiempos,
    color=['#8AA4C4', '#5C7AEA'],
    width=0.4,
    edgecolor='#2C3E50',
)

ax.set_title(
    'Tiempo Promedio de Pago por Plataforma (n = 8 000)',
    fontsize=13,
    fontweight='bold',
    pad=15,
    color='#1A2530',
)
ax.set_ylabel(
    'Tiempo de pago (s)', fontsize=10, fontstyle='italic', color='#1A2530'
)
ax.set_xlabel(
    'Plataforma', fontsize=10, fontstyle='italic', color='#1A2530'
)


ax.set_yticks([])

ax.set_axisbelow(True)
ax.grid(
    True, axis='y', linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9
)

ax.plot(
    [],
    [],
    ' ',
    label='Diferencia = 0.4 s\np = 0.001\n(Sin relevancia práctica)',
)
ax.legend(
    loc='center left',
    bbox_to_anchor=(1.02, 0.5),
    frameon=True,
    facecolor='#F0F4F8',
    edgecolor='#CBD5E1',
    fontsize=9.5,
)

for spine in ax.spines.values():
  spine.set_visible(False)

fig.text(
    0.42,
    -0.03,
    'Estudiante: Katherine Susana Rojas Saborío',
    ha='center',
    fontsize=9,
    fontstyle='italic',
    color='#4A5568',
)

plt.tight_layout()
plt.show()

# gráfico ejercicio 4.3.
import matplotlib.pyplot as plt

equipos = ['Equipo A', 'Equipo B']
tiempos = [4.2, 3.1]

fig, ax = plt.subplots(figsize=(7, 4.5), facecolor='white')
ax.set_facecolor('#D0DCEB')

bars = ax.bar(equipos, tiempos, color=['#8AA4C4', '#5C7AEA'], width=0.4, edgecolor='#2C3E50')

for bar in bars:
    yval = bar.get_height()
    ax.annotate(f'{yval:.1f} días', (bar.get_x() + bar.get_width()/2, yval / 2),
                ha='center', va='center', color='#FFFFFF', fontweight='bold', fontsize=10)

ax.set_title('Tiempo Promedio de Resolución de Quejas', fontsize=13, fontweight='bold', pad=15, color='#1A2530')
ax.set_ylabel('Tiempo de resolución (días)', fontsize=10, fontstyle='italic', color='#1A2530')
ax.set_axisbelow(True)
ax.grid(True, linestyle=':', linewidth=0.8, color='#FFFFFF', alpha=0.9)

ax.plot([], [], ' ', label='Diferencia = 1.1 días\np = 0.006\n(Relevante en práctica)')
ax.legend(loc='center left', bbox_to_anchor=(1.02, 0.5), frameon=True, facecolor='#F0F4F8', edgecolor='#CBD5E1', fontsize=9.5)

for spine in ax.spines.values():
    spine.set_visible(False)

fig.text(0.42, -0.03, 'Estudiante: Katherine Susana Rojas Saborío', ha='center', fontsize=9, fontstyle='italic', color='#4A5568')
plt.tight_layout()
plt.show()